version: "3"

services:
  nginx:
    image: davideromanini/nginx-php
    volumes:
      - .:/var/www
    environment:
      PHP_HOST: "php"
      DOCUMENT_ROOT: /var/www/web
    depends_on:
      - php
    ports:
      - 3333:80
  php:
    image: davideromanini/scrooge-php
    volumes:
      - .:/var/www
    expose:
      - 9000
    depends_on:
      - db
  db:
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: coa
      MYSQL_USER: coa
      MYSQL_PASSWORD: coa
      MYSQL_ROOT_PASSWORD: coa
    command: [
        "mysqld", 
        "--lower_case_table_names=1", 
        "--character-set-server=utf8", 
        "--collation-server=utf8_unicode_ci"
    ]
    
