version: "3"

services:
  nginx:
    image: nginx
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - 3333:80
  php:
    build:
      context: docker/
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www
      - ./docker/php-fpm.conf:/etc/php7/php-fpm.conf
    expose:
      - 9000
    depends_on:
      - db
  db:
    build:
      context: docker/
      dockerfile: Dockerfile-mysql
    image: davideromanini/coa-db
    ports:
      - "3306:3306"
    build:
        context: .
        dockerfile: docker/Dockerfile-mysql
    
