imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

doctrine:
    orm:
        metadata_cache_driver: apcu
        result_cache_driver: apcu
        query_cache_driver: apcu

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      console
        console:
            type:  console
            level: debug
