apiVersion: v1
kind: Service
metadata:
  name: scrooge-php-service
  labels:
    app: scrooge-php
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: scrooge-php
    tier: frontend
